### ISSUE TITLE
bash scripts for generalization experiments using task_arithmetic & ties-merging

### ISSUE THREAD

**Issue by sooyonee** [tanganke/weight-ensembling_MoE#4]
Hi, I am interested in your unseen dataset experiment and trying to retrieve Table 4. I could retrieve accuracy for task arithmetic, however, I'm having difficulty retrieving the result for TIES-merging. Can you share your bash file and dataset setup for experiment in Table 4? Thanks!

**Comment by sooyonee** [comment]
Also, I would appreciate it if you let me know how to setup ood datasets (where to download, if necessary how to split). Thank you!

**Comment by tanganke** [comment]
The scripts to train it can be found at https://github.com/tanganke/weight-ensembling_MoE/tree/master/results

I have uploaded the ood datasets to HuggingFace. You can try to download and use it.
You can reproduce the results for ties-merging using [fusion_bench](https://github.com/tanganke/fusion_bench). 
However, the checkpoints used in FusionBench are fine-tuned by ourselves but in the paper, we use the checkpoints from [task arithmetic](https://github.com/mlfoundations/task_vectors). So the results would be different.

**Comment by sooyonee** [comment]
Thanks for your help. Now I am using fusion bench, and I've got another question. I'm using fusion bench to retrieve accuracies and experiment with my own algorithm, and I'm having difficulty running robustness experiments. For corrupted cases, it does not work with bash files given on the GitHub and project page.
running following commands, I got into the error. It seems that with the following command, 
```
fusion_bench \
    method=task_arithmetic \
        method.scaling_factor=${lambda} \
    modelpool=CLIPVisionModelPool/clip-vit-base-patch32_robustness_clean \
    taskpool=clip-vit-base-patch32_robustness_clean \
    report_save_path=outputs/corrupted/task_arithmetic/clip-vit-base-patch32_robustness_clean_task_arithmetic_${lambda}.json
```
error
```
Error executing job with overrides: ['corruption=contrast', 'method=task_arithmetic', 'method.scaling_factor=0.3', 'modelpool=CLIPVisionModelPool/clip-vit-base-patch32_robustness_corrupted', 'taskpool=clip-vit-base-patch32_robustness_corrupted', 'report_save_path=outputs/clip-vit-base-patch32_robustness_corrupted_contrast_task_arithmetic.json']
Traceback (most recent call last):
  File "/data1/mulan98/anaconda3/envs/moe/bin/fusion_bench", line 8, in <module>
    sys.exit(main())
  File "/data1/mulan98/anaconda3/envs/moe/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/data1/mulan98/anaconda3/envs/moe/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/data1/mulan98/anaconda3/envs/moe/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/data1/mulan98/anaconda3/envs/moe/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/data1/mulan98/anaconda3/envs/moe/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/data1/mulan98/anaconda3/envs/moe/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/data1/mulan98/anaconda3/envs/moe/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/data1/mulan98/anaconda3/envs/moe/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/data1/mulan98/anaconda3/envs/moe/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/data1/mulan98/anaconda3/envs/moe/lib/python3.10/site-packages/fusion_bench/scripts/cli.py", line 38, in main
    program.run()
  File "/data1/mulan98/anaconda3/envs/moe/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "/data1/mulan98/anaconda3/envs/moe/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/data1/mulan98/anaconda3/envs/moe/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/data1/mulan98/anaconda3/envs/moe/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/data1/mulan98/anaconda3/envs/moe/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/data1/mulan98/anaconda3/envs/moe/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/data1/mulan98/anaconda3/envs/moe/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/data1/mulan98/anaconda3/envs/moe/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key run
    full_key: run
    object_type=dict
```
It seems `program: BaseHydraProgram = instantiate(cfg)` in `fusion_bench/scripts/cli.py` is not properly instantiated as a program but becomes Dictionary object. I would appreciate it if you let me know I to tackle it. Thanks!

**Comment by tanganke** [comment]
I have updated the config file to fix this:

https://github.com/tanganke/fusion_bench/blob/23c1218fbaf5082aebe2ab693d0b1db00d6fcd36/config/clip-vit-base-patch32_robustness_corrupted.yaml#L11-L12

run `git pull` to update the code.

**Comment by sooyonee** [comment]
It helped thanks!

Additionally, is there any way to register new task vector obtained from new dataset?
[https://tall-masks.github.io](https://tall-masks.github.io) includes 14, 20 datasets for CLIP experiment and I have their pre-trained weights and datasets.
To include them in the taskpool and modelpool is it possible to do by modifying package source code?
Or is this impossible since data and weights are located in huggingface server?

Thanks a lot for your help.
